### ISSUE TITLE
Ophiuchus is misspelled in ConstellationObjectFilter.java

### ISSUE THREAD

**Issue by InukPhysiker** [alphonzo79/MobileObservingLog#1]
Using the object filter to find the constellation Ophiuchus fails because it is misspelled as Ophiucus.

**Comment by alphonzo79** [comment]
Wow. Thanks for the feedback. I will take care of that as soon as I get a chance. This will give me an opportunity to open up the project and make a couple other improvements too.

Joe

Sent by Outlook for Android

On Wed, May 13, 2015 at 10:37 AM -0700, "InukPhysiker" notifications@github.com wrote:
Using the object filter to find the constellation Ophiuchus fails because it is misspelled as Ophiucus.

---

Reply to this email directly or view it on GitHub:
https://github.com/alphonzo79/MobileObservingLog/issues/1

**Comment by InukPhysiker** [comment]
Hi Joe

No problem. I finally got around to downloading the code but have not 
checked the logs on my Android device as you suggested. I also have an 
un-rooted phone but plan on rooting it as it is a few years old now and 
not under warranty etc...
Although I have used GitHub I am not sure what sort of etiquette to 
follow. I hope submitting an 'issue' for a simple typo wasn't a petty 
thing to do as opposed to sending a private email instead.

If I want to try making changes, would I fork the main branch? I see 
that there are several branches for different versions and wasn't sure 
if I should branch off the highest version number or the main one.

Alan

**Comment by alphonzo79** [comment]
Alan,

No problem at all with creating the issue. Won't be the first I see today and it won't be the last ;).

Those other branches for the various versions were my way of keeping track of where a release was made -- now that I've learned how to use tags I guess that would be the proper way to handle that now. So I would say fork off of master. I think when I open this back up again I'm going to change things to make the chart downloads happen in the background on a service, fancy-up the Object display to handle a chart that is not yet available, and put some stuff in place to track any that didn't download, failed downloads, etc, for background retry. Hopefully that will make it a little easier to use.

Let me know if you need anything else.

Joe

Date: Thu, 14 May 2015 08:48:44 -0700

**Comment by InukPhysiker** [comment]
Hi Joe,

I think I figured out the problem. If the number of target lists is larger
than what a single screen is able to display (at least on my phone) the OK
and Cancel buttons are no longer displayed. Hence it is not possible to add
an object by selecting OK (as shown in attached screenshots).

I have been going through the code and see if I can fix this.

Alan
On May 14, 2015 7:12 AM, "Joe Rowley" notifications@github.com wrote:

Wow. Thanks for the feedback. I will take care of that as soon as I get a
chance. This will give me an opportunity to open up the project and make a
couple other improvements too.

Joe

Sent by Outlook for Android

On Wed, May 13, 2015 at 10:37 AM -0700, "InukPhysiker" <
notifications@github.com> wrote:
Using the object filter to find the constellation Ophiuchus fails because
it is misspelled as Ophiucus.

---

Reply to this email directly or view it on GitHub:
https://github.com/alphonzo79/MobileObservingLog/issues/1

**Comment by alphonzo79** [comment]
Nice, something easy. I just took a quick look -- boy, have my layouts come a long way! I appreciate you taking a look at this. I've still be so tied up with the day job and other projects that I haven't had time to look at it yet. If you want to go ahead and fix Ophiuchus while you're in there I can pull all your changes and push out an update before I get around to doing the improvements I have in mind. Otherwise I'll do the filter fix within a couple weeks here when things calm down.

Let me know if you need anything else.

Joe

Date: Thu, 21 May 2015 17:46:53 -0700

**Comment by alphonzo79** [comment]
This is fixed easily by updating the enum at the bottom of the Contellation Filter file in the ObjectFilter package.

**Comment by alphonzo79** [comment]
Fixing this tonight. Also, in the process I have converted the project to Gradle. So any other work that is being done should be rebased on top of the new structure to avoid merge issues.
